### PR TITLE
reorder

### PR DESCRIPTION
**Pull request by tunnckoCore**
Its unreal to do this.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
The last test fails before I do anything, just fork -> clone -> npm i -> npm test.
I dont know why. There's no logic to be from this change and its not.

**Comment by morishitter** [comment]
Thanks for your PR :)

https://travis-ci.org/morishitter/acss/builds/49743019
This is caused by autoprefixer for renewal of browser vendor prefix.
I'll marge this PR, and then I'll fix test code.

**Comment by tunnckoCore** [comment]
cool :) Maybe you should review/use [ferver](https://github.com/jonathanong/ferver) approach by @jonathanong which is almost the same as semver, but for those of us who "care only about breaking changes".

**Comment by tunnckoCore** [comment]
ppc reminder, choose one - tap or tape :)

**Comment by morishitter** [comment]
Thank you for your advice :)

**Pull request merged**
